export default {
  // Endpoints
  apiVoluntarios                : '/api/catalogo/voluntarios',
  tipoActividadesHV             : '/api/catalogo/tipo/actividadesHV',
  apiSubTipoActividadesHV       : '/api/catalogo/subtipo/actividadesHV',
  apiVoluntarios                : '/api/catalogo/voluntarios',
  apiTiposUsuarios              : '/api/catalogo/tiposUsuarios',
  areasApi                      : '/api/catalogo/areas',
  estadosApi                    : '/api/catalogo/estados',
  tipoAsociadoApi               : '/api/catalogo/tipoAsociado',
  nacionalidadesApi             : '/api/catalogo/nacionalidad',
  tiposSangreApi                : '/api/catalogo/tipoSangre',
  estadoCivilApi                : '/api/catalogo/estadoCivil',
  sexoApi                       : '/api/catalogo/sexo',
  getDelegacionesWithAreasApi   : '/api/catalogo/delegaciones',
  apiEstadosConDelegaciones     : '/api/catalogo/estados/delegaciones',
  apiDelegacionesXTipoCoordinador   : '/api/catalogo/especial/delegaciones',
  apiVoluntariosXDelegacion   : '/api/catalogo/especial/voluntarios',
  apiGetCatalogo              : '/api/get/catalogo',
}
